Update Dockerfile-express

diff --git a/Dockerfile-express b/Dockerfile-express
--- a/Dockerfile-express
+++ b/Dockerfile-express
@@ -35,7 +35,8 @@ RUN if [ ! -f "/app/build/server/index.js" ]; then \
     echo "Build completed successfully!"; \
     fi
 
-RUN find /app -name "redis-session.server.js" -type f
+# Find files starting with "red" or "RED"
+RUN find /app -type f -iname "red*" | sort || echo "File not found"
 
 # --- Início do estágio de Production ---
 FROM node:20.18.0-bookworm-slim
